apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account
  name: account
  # namespace: he
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: account
  strategy: {}
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: dttr278/dev:hne-node-account-service-v2.1.11
          # imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "0.25Gi"
              cpu: "250m"
            limits:
              memory: "0.25Gi"
              cpu: "250m"
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: he-secrets
                  key: MARKETPLACE_MONGODB_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: he-secrets
                  key: JWT_SECRET
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: he-secrets
                  key: X_API_KEY
            - name: SIGN_OPTIONS
              value: "24h"
            - name: WEB3_HTTP_URL
              value: http://rpc2.hne.to
      imagePullSecrets:
        - name: dockerio-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: he
spec:
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: account
  namespace: he
spec:
  scaleTargetRef:
    kind: Deployment
    name: account
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60