apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: station
  name: station
  namespace: he-station
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: station
  strategy: {}
  template:
    metadata:
      labels:
        app: station
    spec:
      containers:
        - name: station
          image: dttr278/dev:hne-station-0.0.3
          # imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '0.25Gi'
              cpu: '250m'
            limits:
              memory: '0.3Gi'
              cpu: '300m'
          env:
            - name: PORT
              value: '3000'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: he-station-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: he-station-secrets
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: he-station-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: he-station-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: he-station-secrets
                  key: DB_DATABASE
            # - name: SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: he-station-secrets
            #       key: JWT_SECRET
            # - name: X_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: he-station-secrets
            #       key: X_API_KEY
            # - name: SIGN_OPTIONS
            #   value: '24h'
            # - name: WEB3_HTTP_URL
            #   value: http://rpc2.hne.to
      imagePullSecrets:
        - name: dockerio-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: station-service
  namespace: he-station
spec:
  selector:
    app: station
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: station
  namespace: he-station
spec:
  scaleTargetRef:
    kind: Deployment
    name: station
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
