---
version: "3"
services:
  station-api:
    image: dttr278/dev:hne-station-latest
    ports:
      - 3007:3000
    environment:
      - PORT=3000
      # - SECRET_KEY=${SECRET_KEY}
      # - SIGN_OPTIONS=${SIGN_OPTIONS}
      # - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      # - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      # - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      # - X_API_KEY=${X_API_KEY}
      # - WEB3_HTTP_URL=${WEB3_HTTP_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: always