---
version: "3"
services:
  station-api:
    build: .
    ports:
      - 5002:3000
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
      - SIGN_OPTIONS=${SIGN_OPTIONS}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
    restart: always